### ISSUE TITLE
10.14请问是怎么样使用呢？

### ISSUE THREAD

**Issue by zhengdaoyi** [i0Ek3/Hackintosh_4_Hasee_Shinelon_A40L#1]
用了黑果小兵a389的10.14，但是在硬盘上更换efi会花屏，不太清楚怎么回事

**Comment by i0Ek3** [comment]
@zhengdaoyi 你可以换个镜像使用，重新制作一个启动盘，然后直接在启动盘的EFI分区覆盖我提供的EFI试试。

**Comment by zhengdaoyi** [comment]
使用镜像自带efi可行，使用ym2008大神的文件花屏，您的efi文件也是如此，黑苹果镜像自带efi缺少亮度与变频调节。
以上看来似乎是镜像有些问题，应该有过修改。

**Comment by i0Ek3** [comment]
@zhengdaoyi 那就行，之后你可以试着调整EFI看看。

**Comment by i0Ek3** [comment]
如果没有其他问题，我就先把这个issue关闭了，日后可以issue其他问题，如果我知道的话。:smile:
