### ISSUE TITLE
A40l 14.3八苹果花屏啊,后面盖子盖上再打开也不行,edid改32也花,怎么办

### ISSUE THREAD

**Issue by bomianmian** [i0Ek3/Hackintosh_4_Hasee_Shinelon_A40L#3]

**Comment by i0Ek3** [comment]
你说的这个问题，我暂且还没有遇到，所以不清楚具体是哪里出了问题。或者你可以试一下这位大哥的EFI：https://github.com/1zilc/K610d-i5-d3-10.14.5-efi-clover
